/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-21-2010
 * 
 * XDoclet definition:
 * @struts.form name="signForm"
 */
public class SignForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** uname property */
	private String uname;

	/** upw property */
	private String upw;

	/** uemail property */
	private String uemail;

	/** ucode property */
	private String ucode;

	/** ucpw property */
	private String ucpw;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the uname.
	 * @return String
	 */
	public String getUname() {
		return uname;
	}

	/** 
	 * Set the uname.
	 * @param uname The uname to set
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/** 
	 * Returns the upw.
	 * @return String
	 */
	public String getUpw() {
		return upw;
	}

	/** 
	 * Set the upw.
	 * @param upw The upw to set
	 */
	public void setUpw(String upw) {
		this.upw = upw;
	}

	/** 
	 * Returns the uemail.
	 * @return String
	 */
	public String getUemail() {
		return uemail;
	}

	/** 
	 * Set the uemail.
	 * @param uemail The uemail to set
	 */
	public void setUemail(String uemail) {
		this.uemail = uemail;
	}

	/** 
	 * Returns the ucode.
	 * @return String
	 */
	public String getUcode() {
		return ucode;
	}

	/** 
	 * Set the ucode.
	 * @param ucode The ucode to set
	 */
	public void setUcode(String ucode) {
		this.ucode = ucode;
	}

	/** 
	 * Returns the ucpw.
	 * @return String
	 */
	public String getUcpw() {
		return ucpw;
	}

	/** 
	 * Set the ucpw.
	 * @param ucpw The ucpw to set
	 */
	public void setUcpw(String ucpw) {
		this.ucpw = ucpw;
	}
}