/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xiaoxie.t.domain.Users;
import com.xiaoxie.t.result.MsgSet_PageNum;
import com.xiaoxie.t.result.User_MsgSet_PageNum;
import com.xiaoxie.t.service.MsgService;

/** 
 * MyEclipse Struts
 * Creation date: 10-17-2010
 * 
 * XDoclet definition:
 * @struts.action
 */
public class DeleteAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String mids=request.getParameter("mid");
		int mId=Integer.parseInt(mids);
		if(new MsgService().deleteMsgByMId(mId)){//如果删除成功
			HttpSession session=request.getSession(false);
			User_MsgSet_PageNum umspn=(User_MsgSet_PageNum)session.getAttribute("umspn");
			Users user=umspn.getUser();
			int uId=user.getuId();
			user.setmNum(user.getmNum()-1);
			umspn.setUser(user);
			int nowPage=Integer.parseInt(session.getAttribute("page").toString());
			int pageSize=10;
			MsgSet_PageNum mspn=new MsgService().getMsgSetByUId(uId, nowPage, pageSize);
			umspn.setMsgSet(mspn.getMsgSet());
		}
		return null;
	}
}