/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xiaoxie.t.domain.Huaex;
import com.xiaoxie.t.service.HuaexService;
import com.xiaoxie.t.struts.form.AddEditForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-22-2010
 * 
 * XDoclet definition:
 * @struts.action path="/edit" name="addEditForm" scope="request"
 */
public class EditAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddEditForm editForm = (AddEditForm) form;// TODO Auto-generated method stub
		String hTitle=editForm.getHtitle();
		String hCon=editForm.getElm1();
		Huaex he=new Huaex(hTitle, hCon);
		if(new HuaexService().addHuaex(he)){
			return mapping.findForward("editsucc");
		}
		return null;
	}
}