/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xiaoxie.t.domain.HuaTi;
import com.xiaoxie.t.domain.Msg;
import com.xiaoxie.t.domain.Url;
import com.xiaoxie.t.domain.Users;
import com.xiaoxie.t.result.User_MsgSet_PageNum;
import com.xiaoxie.t.service.HuaTiService;
import com.xiaoxie.t.service.MsgService;
import com.xiaoxie.t.service.UrlService;

/** 
 * MyEclipse Struts
 * Creation date: 08-29-2010
 * 
 * XDoclet definition:
 * @struts.action path="/fabu" name="fabuForm" scope="request"
 */
public class FabuAction extends Action {
	/*
	 * Generated Methods
	 */

	/**1.��ȡ��Ϣ
	 * 2.������Ϣ
	 *   2.1���˻���
	 *   2.2������ַ
	 * 3.������Ϣ
	 * 4.����֪ͨ
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String mCon=request.getParameter("msg");
		String uIds=request.getParameter("uid");
		String htTitle=null;
		String url=null;
		String surl="";
		
		int uId=Integer.parseInt(uIds);
		try {
			mCon=new String(mCon.getBytes("ISO-8859-1"),"UTF-8");//
			//System.out.println(mCon);
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		String mCon2=mCon;
		String[] strstemp=mCon.split("[a-zA-z]+://[^\\s]+[a-zA-z]");
		if(strstemp.length>1){//寻找网址的正则表达式
			url=mCon.substring(strstemp[0].length()+1,1+mCon.length()-strstemp[1].length());
			//if(url.matches("http://xiaoxie.com/+[a-zA-z0-9]")){//如果已经转化的
				surl="http://xiaoxie.com/"+Integer.toHexString((int)(new Date().getTime())).substring(0,5);
				//System.out.println(Integer.toHexString((int)(new Date().getTime())).length());
				mCon2=strstemp[0]+"<a href='geturl.do?surl="+surl+"'>"+surl+"</a>"+strstemp[1];
				//mCon=mCon2;
				//System.out.println("adjfl");
			//后面是时间的16进制表示形式
			//}
		}
		//mCon.replaceAll("＃","#");System.out.println(mCon);
		if(mCon.indexOf("＃")!=mCon.lastIndexOf("＃")){ //寻找话题
			//System.out.println("有话题");
			String huaCon=mCon.substring(mCon.indexOf("＃")+1,mCon.lastIndexOf("＃"));
			htTitle=huaCon;
			//System.out.println(huaCon);
			huaCon="#<a href="+"search.do?type=huati&scon="+huaCon+">"+huaCon+"</a>#";
			mCon2=mCon.substring(0,mCon.indexOf("＃"))+huaCon+mCon.substring(mCon.lastIndexOf("＃")+1,mCon.length());
			//System.out.println(mCon);
		}
		Msg msg=new Msg(mCon2,uId);
		int mId=new MsgService().addMsg(msg);//把消息发到消息表
		if(mId!=0 && url!=null){   //
			Url urls=new Url(url,surl,mCon2,mId);
			if(new UrlService().addUrl(urls)){
				
			}
		}
		if(mId!=0 && htTitle!=null){   //
			HuaTi ht=new HuaTi(htTitle,mId,uId);
			if(new HuaTiService().addHuaTi(ht)){
				
			}
		}
		//ajax
		HttpSession session=request.getSession(false);
		User_MsgSet_PageNum umspn=(User_MsgSet_PageNum)session.getAttribute("umspn");
		Users user=umspn.getUser();//
		user.setmNum(user.getmNum()+1);//
		List<Msg> msgSet=umspn.getMsgSet();//
		//System.out.println(msgSet.size());
		if(msgSet==null)
			msgSet=new ArrayList<Msg>();
		msgSet.add(0,msg);
		if(msgSet.size()>10){
			msgSet.add(0,msg);
			msgSet.remove(msgSet.size()-1);
		}
		for (Msg msg2 : msgSet) {
			msg2.setUser(user);
		}
		umspn.setMsgSet(msgSet);
		umspn.setUser(user);
		session.setAttribute("umspn", umspn);
		try {//返回xml
			response.setContentType("text/xml");
			PrintWriter out=response.getWriter();
			out.println("<?xml version='1.0' encoding='UTF-8'?>");
			out.println("<msgres>");
			out.println("<msgid>"+mId+"</msgid>");
			out.println("<msgcon>"+mCon+"</msgcon>");
			out.println("<msgsurl>"+surl+"</msgsurl>");
			out.println("</msgres>");
			out.flush();
			out.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}