/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xiaoxie.t.domain.Follow;
import com.xiaoxie.t.domain.Users;
import com.xiaoxie.t.result.MsgSet_PageNum;
import com.xiaoxie.t.result.User_MsgSet_PageNum;
import com.xiaoxie.t.service.FollowService;
import com.xiaoxie.t.service.MsgService;

/** 
 * MyEclipse Struts
 * Creation date: 10-19-2010
 * 
 * XDoclet definition:
 * @struts.action
 */
public class FollowAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String uIds=request.getParameter("uid");
		String vuIds=request.getParameter("vuid");
		int uId=Integer.parseInt(uIds);
		int vuId=Integer.parseInt(vuIds);
		if(new FollowService().addFollow(new Follow(vuId,uId))){//添加成功
			HttpSession session=request.getSession(false);
			User_MsgSet_PageNum umspn=(User_MsgSet_PageNum)session.getAttribute("umspn");
			Users user=umspn.getUser();
			user.setFowNum(user.getFowNum()+1);
			umspn.setUser(user);
			MsgSet_PageNum mspn=new MsgService().getMsgSetByUId(uId, 1, 10);
			umspn.setMsgSet(mspn.getMsgSet());
			umspn.setPageNum(mspn.getPageNum());
			//被访问者
			session.setAttribute("umspn", umspn);
			request.setAttribute("havefollow", "yiguanzhu");
		}
		return null;
	}
}