/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.action;

import java.io.IOException;
import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xiaoxie.t.domain.Forword;
import com.xiaoxie.t.domain.Msg;
import com.xiaoxie.t.domain.Users;
import com.xiaoxie.t.result.MsgSet_PageNum;
import com.xiaoxie.t.result.User_MsgSet_PageNum;
import com.xiaoxie.t.service.ForwordService;
import com.xiaoxie.t.service.MsgService;
import com.xiaoxie.t.service.UsersService;

/** 
 * MyEclipse Struts
 * Creation date: 10-19-2010
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ForwordAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String forcon=request.getParameter("forcon");//转发时加的评论
		String mids=request.getParameter("mid");//转发的消息的mid
		String msguid=request.getParameter("msguid");//转发的消息的拥有者的uid
		String formcon=request.getParameter("mcon");//转发内容
		
		try {
			formcon=new String(formcon.getBytes("ISO-8859-1"),"UTF-8");
			if(forcon!="" || forcon !=null){
				forcon=new String(forcon.getBytes("ISO-8859-1"),"UTF-8");
			}else{
				forcon="转发微博~";
			}
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
		int mId=Integer.parseInt(mids);
		int uId=Integer.parseInt(msguid);
		HttpSession session=request.getSession(false);
		User_MsgSet_PageNum umspn=(User_MsgSet_PageNum)session.getAttribute("umspn");
		int foruId=umspn.getUser().getuId();
		//自己能转发自己的消息吗？
		Forword forword=new Forword(forcon, mId, uId, foruId);
		if(new ForwordService().addForword(forword)){//转发表添加成功
			//构造一条消息，并插入到消息表中
			int muId=uId;
			String muName=new UsersService().getUserByUId(uId).getuName();
			String mCon=forcon+"<a href=visit.do?vuid="+muId+">@"+muName+"</a>:"+formcon;
			Msg msg=new Msg(mCon, foruId);
			int msId=new MsgService().addMsg(msg);
			if(msId!=0){// 消息添加成功
				MsgSet_PageNum mspn=new MsgService().getMsgSetByUId(foruId, 1, 10);
				umspn.setMsgSet(mspn.getMsgSet());
				umspn.setPageNum(mspn.getPageNum());
				Users user=umspn.getUser();
				user.setmNum(user.getmNum()+1);
				user.setForNum(user.getForNum()+1);
				umspn.setUser(user);
				session.setAttribute("umspn", umspn);
				try {
					response.getWriter().print(msId);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}
		return null;
	}
}