/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xiaoxie.t.domain.Users;
import com.xiaoxie.t.result.MsgSet_PageNum;
import com.xiaoxie.t.service.FollowService;
import com.xiaoxie.t.service.MsgService;
import com.xiaoxie.t.service.UsersService;

/** 
 * MyEclipse Struts
 * Creation date: 10-21-2010
 * 
 * XDoclet definition:
 * @struts.action
 */
public class GuangboAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int nowPage=1;
		int pageSize=10;
		int allnum=new MsgService().getAllMsgNum();
		int pageNum=(allnum%pageSize==0)?(allnum/pageSize):(allnum/pageSize+1);
		if(request.getParameter("page")==null){
			nowPage=1;
		}else{
			nowPage=Integer.parseInt(request.getParameter("page"));
			if(request.getParameter("type").equals("up")){//上页
				if(nowPage>1)
					nowPage=nowPage-1;
			}else if(request.getParameter("type").equals("down")){
				if(nowPage<pageNum)
					nowPage=nowPage+1;
			}
		}
		MsgSet_PageNum mspn=new MsgService().getAllMsg(nowPage,pageSize);
		request.setAttribute("mspn", mspn);
		request.setAttribute("page", nowPage);
		
		//广播达人
		List<Users> userSet=new UsersService().getFoTopUsers(11);
		for (Users users : userSet) {
			int uId=users.getuId();
			users.setFowedNum(new FollowService().getFowedNumByUId(uId));
		}
		request.setAttribute("userSet", userSet);
		return mapping.findForward("gbsucc");
	}
}