/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xiaoxie.t.domain.HuaTi;
import com.xiaoxie.t.domain.Huaex;
import com.xiaoxie.t.service.HuaTiService;
import com.xiaoxie.t.service.HuaexService;

/** 
 * MyEclipse Struts
 * Creation date: 10-30-2010
 * 
 * XDoclet definition:
 * @struts.action
 */
public class HuatiAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//热门话题的相关文章
		int num=3;
		List<HuaTi> htSet=new HuaTiService().findTopHuaTi(num);
		List<Huaex> heSet=new ArrayList<Huaex>();
		for (HuaTi huaTi : htSet) {
			String huaTitle=huaTi.getHuaTitle();
			List<Huaex> heSetTemp=new HuaexService().getHuaexByHTitle(huaTitle);
			for (Huaex huaex : heSetTemp) {
				heSet.add(huaex);
			}
		}
		request.setAttribute("heSet", heSet);
		return mapping.findForward("succ");
	}
}