/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xiaoxie.t.domain.Users;
import com.xiaoxie.t.result.MsgSet_PageNum;
import com.xiaoxie.t.result.User_MsgSet_PageNum;
import com.xiaoxie.t.service.MsgService;
import com.xiaoxie.t.service.UsersService;
import com.xiaoxie.t.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-22-2010
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		String uEmail=loginForm.getEmail();
		String uPW=loginForm.getPw();
		HttpSession session=request.getSession();
		if(uEmail==null || uPW==null){
			User_MsgSet_PageNum oldumspn=(User_MsgSet_PageNum)session.getAttribute("umspn");
			uEmail=oldumspn.getUser().getuEmail();
			uPW=oldumspn.getUser().getuPW();
		}
		Users us=new Users(uEmail,uPW);
		Users user=new UsersService().checkLogin(us);//
		if(user!=null){
		    int uId=user.getuId();
			MsgSet_PageNum mspn=new MsgService().getMsgSetByUId(uId, 1, 10);
			User_MsgSet_PageNum umspn=null;
			if(mspn!=null){
				umspn=new User_MsgSet_PageNum(user,mspn.getMsgSet(),mspn.getPageNum());
			}else{
				umspn=new User_MsgSet_PageNum(user,null,0);
			}
			session.setAttribute("umspn", umspn);
			session.setAttribute("page", 1);
			return mapping.findForward("loginsucc");
		}
		return null;
	}
}