/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xiaoxie.t.domain.Msg;
import com.xiaoxie.t.domain.Users;
import com.xiaoxie.t.service.MsgService;
import com.xiaoxie.t.service.UsersService;

/** 
 * MyEclipse Struts
 * Creation date: 08-20-2010
 * 
 * XDoclet definition:
 * @struts.action
 */
public class StartAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List<Msg> newMsgSet=new MsgService().getNewMsg(8);
		List<Users> topUserSet=new UsersService().getTopUsers(10);
		HttpSession session=request.getSession();
		session.setAttribute("nms", newMsgSet);
		session.setAttribute("tus", topUserSet);
		return mapping.findForward("startsucc");
	}
}