/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoxie.t.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xiaoxie.t.domain.Users;
import com.xiaoxie.t.result.MsgSet_PageNum;
import com.xiaoxie.t.result.User_MsgSet_PageNum;
import com.xiaoxie.t.service.FollowService;
import com.xiaoxie.t.service.MsgService;
import com.xiaoxie.t.service.UsersService;

/** 
 * MyEclipse Struts
 * Creation date: 01-18-2005
 * 
 * XDoclet definition:
 * @struts.action
 */
public class VisitAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String vuIds=request.getParameter("vuid");
		String vmIds=request.getParameter("vmid");
		int vmId=0;
		int vuId=0;
		Users user=null;
		if(vuIds!=null || vmIds!=null){
		if(vuIds==null){
			vmId=Integer.parseInt(vmIds);
			user=new UsersService().getUserByMId(vmId);
			vuId=user.getuId();
		}else if(vmIds==null){
			vuId=Integer.parseInt(vuIds);
			user=new UsersService().getUserByUId(vuId);
		}}
		if(vuIds==null && vmIds==null){
			vuId=3;
			user=new UsersService().getUserByUId(3);
		}
		user=new UsersService().checkLogin(user);
		HttpSession session=request.getSession(false);
		if(session.getAttribute("vumspn")!=null){
			session.removeAttribute("vumspn");
		}
		if(session.getAttribute("umspn")!=null){
			User_MsgSet_PageNum umspn=(User_MsgSet_PageNum)session.getAttribute("umspn");
			int uId=umspn.getUser().getuId();
			if(new FollowService().getFIdByUIdFUId(vuId, uId)!=0){//表明已经关注了
				request.setAttribute("havefollow", "yiguanzhu");
			}
		}
		int nowPage=1;
		int pageSize=10;
		MsgSet_PageNum mspn=new MsgService().getMsgSetByUId(vuId, nowPage, pageSize);
		User_MsgSet_PageNum vumspn=new User_MsgSet_PageNum(user, mspn.getMsgSet(), mspn.getPageNum());
		session.setAttribute("vumspn", vumspn);
		return mapping.findForward("succ");
	}
}